apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: 447866867700.dkr.ecr.us-west-2.amazonaws.com/stefan-demo:latest
        command: ["/bin/bash", "-c", "/sample-app/bin/sample-app"]
        ports:
        - containerPort: 8080
  strategy: {}
    # canary:
    #   steps:
    #   - setWeight: 20
    #   - pause: {}
    #   - setWeight: 40
    #   - pause: {duration: 120s}
    #   - setWeight: 60
    #   - pause: {duration: 120s}
    #   - setWeight: 80
    #   - pause: {duration: 120s}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: after
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: sample-app-integration-tests
        image: 447866867700.dkr.ecr.us-west-2.amazonaws.com/stefan-demo:latest
        command: ["/bin/bash", "-c", "/sample-app/bin/sample-app integration"]
      restartPolicy: Never
  backoffLimit: 0
---
kind: Service 
apiVersion: v1 
metadata:
  name: sample-app-service 
spec:
  selector:
    app: sample-app
  ports:
    - name: sample-app-service-port
      port: 8080 
      targetPort: 80