apiVersion: argoproj.io/v1alpha1
kind: Rollout
# apiVersion: apps/v1
# kind: Deployment
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        imagePullPolicy: Always
        image: 447866867700.dkr.ecr.us-west-2.amazonaws.com/stefan-demo:v2.0.1
        command:
          - /bin/bash
          - -c
          - /sample-app/bin/sample-app
        ports:
        - containerPort: 7833
  # strategy: {}
  strategy: 
    canary:
      analysis:
        templates:
        - templateName: integration-tests
      steps:
      - setWeight: 80
      - pause: {duration: 20s}
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: integration-tests
  # annotations:
  #   argocd.argoproj.io/hook: PostSync
  #   argocd.argoproj.io/hook-delete-policy: HookSucceeded
  #   argocd.argoproj.io/sync-wave: "0"
spec:
  metrics:
  - name: integration-tests
    successCondition: result.state.exitCode == 0
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: sample-app-integration-tests
                image: 447866867700.dkr.ecr.us-west-2.amazonaws.com/stefan-demo:latest
                imagePullPolicy: Always
                command:
                  - /bin/bash
                  - -c
                  - |
                    sleep 5
                    /sample-app/bin/sample-app integration sample-app-service:7833
              restartPolicy: Never  
---
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: after-deploy
#   annotations:
#     argocd.argoproj.io/hook: PostSync
#     argocd.argoproj.io/hook-delete-policy: HookSucceeded
#     argocd.argoproj.io/sync-wave: "0"
# spec:
#   template:
#     spec:
#       containers:
#       - name: sample-app-integration-tests
#         image: 447866867700.dkr.ecr.us-west-2.amazonaws.com/stefan-demo:latest
#         command: 
#           - /bin/bash
#           - -c
#           - |
#             sleep 5
#             /sample-app/bin/sample-app integration sample-app-service:7833
#       restartPolicy: Never
#   backoffLimit: 1
---
kind: Service 
apiVersion: v1 
metadata:
  name: sample-app-service 
spec:
  selector:
    app: sample-app
  ports:
    - name: sample-app-service-port
      port: 7833 
      targetPort: 7833