apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
  replicas: 0
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: stefanmcshane/sample-app:latest
        ports:
        - containerPort: 8080
  strategy:
    canary:
      steps:
      - setWeight: 20
      # The following pause step will pause the rollout indefinitely until manually resumed.
      # Rollouts can be manually resumed by running `kubectl argo rollouts promote ROLLOUT`
      - pause: {}
      - setWeight: 40
      - pause: {duration: 120s}
      - setWeight: 60
      - pause: {duration: 120s}
      - setWeight: 80
      - pause: {duration: 120s}
---
kind: Service 
apiVersion: v1 
metadata:
  name: sample-app-service 
spec:
  selector:
    app: sample-app
  ports:
    - name: sample-app-service-port
      port: 8080 
      targetPort: 80