name: On Merge

# on:
#   pull_request:
#     branches: [ main ]
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and Publish image
    runs-on: ubuntu-latest

    steps:
    - name: Change git URLs to use SSH
      run: echo -e '[url "git@github.com:"]\n  insteadOf = "https://github.com/"' >> ~/.gitconfig

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive
        ssh-key: ${{ secrets.SSH_MACHINE_KEY }}
    
    - name: Build and Publish image
      run: |
        echo ${{ secrets.IMAGE_REGISTRY_PASSWORD }} | docker login --username stefanmcshane --password-stdin
        docker build  -t "stefanmcshane/${{ github.event.repository.name }}:latest" -t "stefanmcshane/${{ github.event.repository.name }}:${{github.sha}}" . -f Dockerfile
        docker push stefanmcshane/${{ github.event.repository.name }}:latest
        docker push stefanmcshane/${{ github.event.repository.name }}:${{github.sha}}

    - name: Build manifest for dev
      uses: stefanprodan/kube-tools@v1
      with: 
        kustomize: 4.5.2
        command: |
          cd deploy/dev
          kustomize edit set image "*:${{github.sha}}" 
          kustomize build
