name: On Merge

# on:
#   pull_request:
#     branches: [ main ]
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and Publish Image to dev
    runs-on: ubuntu-latest

    steps:
    - name: Change git URLs to use SSH
      run: echo -e '[url "git@github.com:"]\n  insteadOf = "https://github.com/"' >> ~/.gitconfig

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive
        ssh-key: ${{ secrets.SSH_MACHINE_KEY }}
    
    # - name: Build and Publish image
    #   run: |
    #     echo ${{ secrets.IMAGE_REGISTRY_PASSWORD }} | docker login --username stefanmcshane --password-stdin
    #     docker build  -t "stefanmcshane/${{ github.event.repository.name }}:latest" -t "stefanmcshane/${{ github.event.repository.name }}:${{ github.sha }}" . -f Dockerfile
    #     docker push stefanmcshane/${{ github.event.repository.name }}:latest
    #     docker push stefanmcshane/${{ github.event.repository.name }}:${{ github.sha }}

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1

    - name: Build manifest for dev
      id: generate-deployment-manifest
      run: |
        cd deploy/dev
        kustomize edit set image "*:${{github.sha}}" 
        echo ::set-output name=tagged_manifest::$(kustomize build | base64)

    - name: Connect to Deployment repo
      uses: getsentry/action-github-app-token@v1
      id: generate-token
      with:
        app_id: ${{ secrets.GH_APP_ID }}
        private_key: ${{ secrets.GH_APP_KEY }}

    - name: Checkout deployment repo
      uses: actions/checkout@v2
      with:
        submodules: recursive
        ssh-key: ${{ secrets.SSH_MACHINE_KEY }}
        repository: stefanmcshane/deployment

    - name: Update manifest in deployment repo
      run: |
        echo ${{ steps.generate-deployment-manifest.outputs.tagged_manifest }} > dev/manifest.yml

    - name: Create Pull Request in deployment repo
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ steps.generate-token.outputs.token }}
        title: Update ${{ github.event.repository.name }} manifest for dev
        body: Update ${{ github.event.repository.name }} manifest for dev to ${{ github.sha }}