name: Create and Publish Image

# on:
#   pull_request:
#     branches: [ main ]
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and publish container
    runs-on: ubuntu-latest

    steps:
    - name: Change git URLs to use SSH
      run: echo -e '[url "git@github.com:"]\n  insteadOf = "https://github.com/"' >> ~/.gitconfig

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive
        ssh-key: ${{ secrets.SSH_MACHINE_KEY }}
      run: |
        	docker build  -t "stefanmcshane/${{github.repository}}:latest" -t "stefanmcshane/${{github.repository}}:${{github.sha}}" .
          docker push stefanmcshane/${{github.repository}}:latest
          docker push stefanmcshane/${{github.repository}}:${{github.sha}}