name: Go Build & Test

# on: push
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Lint and Unit tests
    runs-on: ubuntu-latest
    container:
      image: stefanmcshane/go-ci-tools:latest
      credentials:
          username: stefanmcshane
          password: ${{ secrets.IMAGE_REGISTRY_PASSWORD}}
    
    steps:
    - name: Fix up git URLs
      run: echo -e '[url "git@github.com:"]\n  insteadOf = "https://github.com/"' >> ~/.gitconfig

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive
        ssh-key: ${{ secrets.SSH_MACHINE_KEY }}
      
    - name: Lint
      run: make lint

    - name: Run unit tests
      run: make test
      